id: I788C209B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:47:04+00:00'
last_modified: '2022-06-09T04:25:59.294134+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13776
  title: ཚན་རྩལ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    04F3:
      image_group_id: I1KG15260
      title: Volume 1 of tshan rtsal rig pa'i spyi bshad/
      total_pages: 138
      order: 1
      base_file: 04F3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
