id: P008091
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG13776
  title: ཚན་རྩལ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  volumes:
    86b02027ebd5472c84b768fb7ad01609:
      image_group_id: I1KG15260
      title: Volume 1 of tshan rtsal rig pa'i spyi bshad/
      volume_number: 1
      total_pages: 138
      base_file: v001.txt
