id: P008091
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13776
  title: ཚན་རྩལ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  volumes:
    6a60e7ad6fa04f06ba1c82196e81c6ee:
      image_group_id: I1KG15260
      title: ''
      volume_number: 1
      total_pages: 138
ebook_metadata:
  title: ཚན་རྩལ་རིག་པའི་སྤྱི་བཤད།
  author: ''
  sku: P008091
  cover: cover.jpg
  layers:
  - pagination
